apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: fraud-detection
data:
  PYTHONUNBUFFERED: "1"
  ENVIRONMENT: "kubernetes"
  MLFLOW_TRACKING_URI: "sqlite:////app/mlflow.db"
