# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS deps

WORKDIR /app

ENV NPM_CONFIG_FETCH_RETRIES=5
ENV NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000
ENV NPM_CONFIG_FETCH_TIMEOUT=300000

COPY apps/backend/package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci \
    --prefer-offline \
    --no-audit \
    --no-fund


FROM deps AS builder

WORKDIR /app

ENV DATABASE_URL="postgresql://fraud_user:fraud_password@backend-postgres:5432/fraud_auth_db?schema=public"

COPY apps/backend/nest-cli.json ./
COPY apps/backend/tsconfig*.json ./
COPY apps/backend/prisma ./prisma
COPY apps/backend/prisma.config.ts ./prisma.config.ts
COPY apps/backend/src ./src

RUN npm run prisma:generate
RUN npm run build


FROM deps AS prod-deps

RUN npm prune \
    --omit=dev \
    --no-audit \
    --no-fund


FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000

COPY apps/backend/package*.json ./
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/generated ./dist/generated

EXPOSE 4000

CMD ["sh", "-c", "if [ -f dist/main.js ]; then node dist/main.js; else node dist/src/main.js; fi"]
