FROM node:22-alpine AS deps

WORKDIR /app

COPY apps/backend/package*.json ./

RUN npm ci


FROM node:22-alpine AS builder

WORKDIR /app

ENV DATABASE_URL="postgresql://fraud_user:fraud_password@backend-postgres:5432/fraud_auth_db?schema=public"

COPY --from=deps /app/node_modules ./node_modules
COPY apps/backend/package*.json ./
COPY apps/backend/nest-cli.json ./
COPY apps/backend/tsconfig*.json ./
COPY apps/backend/prisma ./prisma
COPY apps/backend/prisma.config.ts ./prisma.config.ts
COPY apps/backend/src ./src

RUN npm run prisma:generate
RUN npm run build


FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=4000

COPY apps/backend/package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/generated ./dist/generated

EXPOSE 4000

CMD ["sh", "-c", "if [ -f dist/main.js ]; then node dist/main.js; else node dist/src/main.js; fi"]
