.git
.github
.venv
venv
env

**/__pycache__
**/.pytest_cache
**/.mypy_cache
**/.ruff_cache

**/node_modules
**/.next
**/dist
**/build
**/coverage

*.log
.DS_Store
.vscode
.idea

mlruns
mlruns-ci
mlflow.db
mlflow-ci.db
mlartifacts

apps/ml-service/data/*
!apps/ml-service/data/.gitkeep
