.git
.github
.venv
venv
env

**/node_modules
**/dist
**/.next
**/coverage

**/__pycache__
**/.pytest_cache

*.log
.DS_Store
.vscode
.idea

apps/backend/.env
apps/backend/src/generated
apps/backend/dist
