apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api
  namespace: fraud-detection
  labels:
    app: fraud-detection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection-api
  template:
    metadata:
      labels:
        app: fraud-detection-api
    spec:
      containers:
        - name: fraud-detection-api
          image: achintha2003/fraud-ml-service:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: fraud-detection-config
                  key: PYTHONUNBUFFERED
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: fraud-detection-config
                  key: PYTHONPATH
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: fraud-detection-config
                  key: MLFLOW_TRACKING_URI
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: ml-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-api-service
  namespace: fraud-detection
spec:
  type: NodePort
  selector:
    app: fraud-detection-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
