apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: fraud-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: fraud-detection
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:v3.14.0
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow
          command:
            - mlflow
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --allowed-hosts
            - mlflow-service:5000,localhost:*,127.0.0.1:*
            - --backend-store-uri
            - sqlite:////mlflow/mlflow.db
            - --serve-artifacts
            - --artifacts-destination
            - /mlflow/artifacts
            - --default-artifact-root
            - mlflow-artifacts:/
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 40
            periodSeconds: 20
      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: fraud-detection
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30051
