apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-pvc
  namespace: fraud-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fraud-detection-trainer
  namespace: fraud-detection
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: fraud-detection-trainer
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: achintha2003/fraud-ml-service:k8s
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              python scripts/create_ci_model_artifacts.py
              python -m src.training.train_business_model
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: fraud-detection-config
                  key: PYTHONUNBUFFERED
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: fraud-detection-config
                  key: PYTHONPATH
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: fraud-detection-config
                  key: MLFLOW_TRACKING_URI
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: ml-models-pvc
